config/routes.rb
Rails.application.routes.draw do

  get 'todos/index' =>'todos#index', as: 'index'

  root to: 'todos#index'

  get 'todos/show/:id' =>'todos#show', as: 'show'

  get 'todos/new' =>'todos#new', as: 'new'

  get 'todos/:id/edit' => 'todos#edit', as: 'edit'

  patch 'todos/:id/update' => 'todos#update', as: 'update'

  post 'todos/create' =>'todos#create', as: 'create'

  patch 'todos/:id/toggle_completed' => 'todos#toggle_completed', as:'toggle'

  delete 'todos/:id/destroy' => 'todos#destroy', as: 'delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  validates :title, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @mytodos = TodoItem.all
  end

  def show
    @mytodo = TodoItem.first
  end

  def new
    @mytodo = TodoItem.new
  end

  def create
    s1 = TodoItem.new
    s1.title = params[:todo_item][:title]
    s1.description = params[:todo_item][:description]
    s1.finished = params[:todo_item][:finished]
    s1.due_date = params[:todo_item][:due_date]
    s1.save
    redirect_to action: "index"
  end

  def edit
    @mytodo = TodoItem.find(params[:id].to_i)
  end
  def update
    @mytodo = TodoItem.find(params[:id].to_i)
    @mytodo[:title] = params[:todo_item]["title"]
    @mytodo[:description] = params[:todo_item]["description"]
    @mytodo[:finished] = params[:todo_item]["finished"]
    @mytodo[:due_date] = params[:todo_item]["due_date"]
    @mytodo.save
    if @mytodo.finished == true
      @mytodo.completed_at = DateTime.now
      @mytodo.save
  end
  redirect_to action: "index"
  end

  def toggle_completed
      @mytodo = TodoItem.find(params[:id].to_i)
      @mytodo.update(finished: !@mytodo.finished)
      redirect_to action: "index"
    end
    
  def destroy
    @mytodo = TodoItem.destroy(params[:id].to_i)
    redirect_to action: "index"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todosform.html.erb
<section>
<%= form_for @mytodo, url: create_path do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :due_date %>
<%= f.date_field :due_date %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :complete %>
<%= f.check_box :finished %>
<%= f.submit %>
<%end%>
</section>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<h1>Update a Todos</h1>

<section>
<%= form_for @mytodo, url: update_path do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :due_date %>
<%= f.date_field :due_date %>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :complete %>
<%= f.check_box :finished %>
<%= f.submit %>
<%end%>
</section>

app/views/todos/index.html.erb
<h1>My Todo List</h1>
<p><%= link_to('Add New Todo', new_path) %></p>
<% @mytodos.each do |todo|%>
      <article class="title">
    <h3> <%= todo.title %><h3>
    <h2> <%= link_to("More details", show_path(todo[:id]))%></h2>
          <% if todo.finished != true && todo.due_date < DateTime.now %>
               <h2>OVER DUE!!<h2>
               <h3> <%= todo.due_date %><h3>
          <% else %>
          <h3> <%= todo.due_date %><h3>
          <% end %>
    <p class="link"><%= link_to('Edit', edit_path(todo.id)) %></p>
        <% if todo.finished
        button_label = "Task Complete"
        else
        button_label = "Task Not Complete"
        end %>
      <p><%= button_to button_label, toggle_path(todo.id), method: :patch %></p>
      <p><%= button_to 'Delete', {action: "destroy", id: todo.id}, method: :delete, data: {confirm: "Are you sure?"} %></p>
  <%end%>
    </article>

app/views/todos/new.html.erb
<h1>Create a new Todo</h1>
<%= render partial: "todosform" %>

app/views/todos/show.html.erb
<h1><%= @mytodo.title %></h1>

<article>

    <h3> <%= @mytodo.description %><h3>
    <h3> <%= @mytodo.due_date %><h3>
        <%if @mytodo.finished
           status = "Task Complete"
        else
        status = "Task Not Complete"
        end%>

      <h3> <%= status %><h3>
  <p><%= link_to('Edit', edit_path(@mytodo.id)) %></p>
  <p><%= button_to 'Delete', {action: "destroy", id: @mytodo.id}, method: :delete, data: {confirm: "Are you sure?"} %></p>


</article>